apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: c2
  region: us-east-1

nodeGroups:
  - name: ng-1
    instanceType: m6i.large
    desiredCapacity: 2
    volumeSize: 80
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
  - name: ng-2
    instanceType: c6g.large
    desiredCapacity: 2
    volumeSize: 80
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key

